### ISSUE TITLE
Genres of mm:MusicEntity

### ISSUE THREAD

**Issue by guillotel-nothmann** [polifonia-project/music-meta-ontology#13]
mm:hasGenre is currently restricted to the range of mm:MusicArtist. We need to express that a mm:MusicEntity belongs to a specific mm:Genre.  Could we change this ?

**Comment by jonnybluesman** [comment]
This is feasible and makes perfect sense to me; as a `mm:Genre` could in principle be associated to virtually anything. I believe we can relax, or simply remove the restriction.

**Comment by jonnybluesman** [comment]
This has been solved after commit cba2971a22d356e441d9fa6a08bac98f6a4d70e8
